### ISSUE TITLE
Event request

### ISSUE THREAD

**Issue by SummerTheMo** [bytewife/bay.lgbt#6]
Good afternoon,

my name is Summer and I was asked to post my new meet up group event information here (I have no idea how to use GitHub but am willing to learn and take feedback).

I run the East Bay Neurodivergence Meet Up group and am trying to organize our first event on Monday at 7 at victory point cafe. I have not talked to the vendor yet but am willing to (I’ve never hosted either so this is all new to me).

looking forward to hearing from you,
Summer

**Comment by ivyraine** [comment]
Hey Summer! Could you shoot me an email with all the event information you have? You can find me at ivyemberraine (@) gmail (dot) com .

**Comment by SummerTheMo** [comment]
Thanks for getting back to me!

“Come one come all, bring a friend, game, or your latest hyperfixation!
Please support the cafe and find a drink of choice while mingling with fun
company.

To play games from the cafe or your own costs $8. This did not occur to me
until after I chose this venue. If this is prohibitive, talk to me prior
and I can go halfsies with up to 5 people.

Free parking Is available on walnut and we have secured the large table
outside the front of the cafe. Find your host in a blue floral shirt!

This is my first event I’ve organized so please go easy on me. I’m open to
feedback on how to make things even better :).”

Starts at 7, ends at 9, at victory point cafe in Berkeley tonight
